import { useState } from "react";

export default function PlantForm({ onCreate, loading }) {
  const [name, setName] = useState("");
  const [category, setCategory] = useState("");

  async function handleSubmit(e) {
    e.preventDefault();
    const payload = { name: name.trim() };
    const cat = category.trim();
    if (cat) payload.category = cat;
    if (!name.trim()) return;

    await onCreate({
      name: name.trim(),
      category: category.trim() || "",
    });

    setName("");
    setCategory("");
  }

  return (
    <form
      onSubmit={handleSubmit}
      style={{ display: "grid", gap: 10, maxWidth: 420 }}
    >
      <h3>Add Plant</h3>

      <label>
        Name *
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
          style={{ width: "100%", padding: 8 }}
        />
      </label>

      <label>
        Category (optional)
        <input
          value={category}
          onChange={(e) => setCategory(e.target.value)}
          style={{ width: "100%", padding: 8 }}
        />
      </label>

      <button disabled={loading} style={{ padding: 10 }}>
        {loading ? "Adding..." : "Add Plant"}
      </button>

      <p style={{ opacity: 0.7, margin: 0 }}>
        Icon is auto-generated by backend (🌱 + name).
      </p>
    </form>
  );
}
