"""fixed validation kwargs

Revision ID: 2e950757f248
Revises: 8fb6167a6070
Create Date: 2025-12-30 17:02:26.075228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e950757f248'
down_revision = '8fb6167a6070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plants_per_sq', sa.Integer(), nullable=False))
        batch_op.drop_column('plants_per_square')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plants_per_square', sa.INTEGER(), nullable=False))
        batch_op.drop_column('plants_per_sq')

    # ### end Alembic commands ###
